### PR TITLE
Fix incorrect MIME/Content-Type for JavaScript

### LINKED ISSUE #4467: notebook gives blank page when start
It used to work fine until I changed python to lower version today(3.7 to 3.6). The jupyter notebook keeps giving me blank page when started. I changed the version back and it doesn't help. No error in the terminal. The error in the browser are as follows:
`Refused to execute script from '<URL>' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/preact/index.js?v=00a2fac73c670ce39ac53d26640eb542' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/proptypes/index.js?v=c40890eb04df9811fcc4d47e53a29604' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/preact-compat/index.js?v=aea8f6660e54b18ace8d84a9b9654c1c' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/tree/js/main.min.js?v=ab9f3a6cf8347df927864d58cfad7931' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:24 Uncaught ReferenceError: require is not defined
    at VM26 tree:24`

I check some other posts which said to clean browser caches and cookies which doesn't help for my case. Any idea about how to fix this problem?

### PR DESCRIPTION
**Pull request by ciaranlangton**
# Problem
Tornado serves JavaScript files with `Content-Type: text/plain`, which causes the browser to reject loading the JavaScript, due to Strict MIME checking enabled in the last version. This problem appears to manifest only on Windows hosted notebooks.

# Solution
Similar to the CSS fix, add in a mimetypes override for .js files

closes #4467

### CODE REVIEW

**Comment by rachpark** [comment]
thanks! it works very well now! 
I love you!

**Comment by ejmoya** [comment]
In w10 I have the same problem but it does not solve only with this. To solve it, I went to the directory **"AppData\Local\Programs\Python\Python37\Lib\site-packages\notebook\templates"** and edit the file "page.html" on line 18, changing the double quotes with single quotes.
Before:
`<script src="{{static_url("components/es6-promise/promise.min.js")}}" type="text/javascript" charset="utf-8"></script>`

After:
`<script src="{{static_url('components/es6-promise/promise.min.js')}}" type="text/javascript" charset="utf-8"></script>`

**Comment by lovettchris** [comment]
I had the blank page problem today, and this PR fixed it, thanks.  Just had to do CTRL+F5 to force refresh and my Jupyter notebooks are back in business.  Thanks!

**Comment by AnMa12** [comment]
> I had the blank page problem today, and this PR fixed it, thanks. Just had to do CTRL+F5 to force refresh and my Jupyter notebooks are back in business. Thanks!

Thank you sir!

**Comment by IJM5157** [comment]
Thank you so much for fixing this, really hope this is merged soon.

**Comment by ghernie** [comment]
Thanks a lot mate !! It solved my MINE issue 👍

**Comment by deepandas11** [comment]
How to use this?

**Comment by BLGAmazingJ** [comment]
Thx^_^
Problem fixed.

**Comment by BLGAmazingJ** [comment]
> How to use this?

You need to locate noteapp.py and override that part.

**Comment by gaborvecsei** [comment]
Thanks for the fix! ❤️ 
Why is this not merged? 🤔

**Comment by kzq666666** [comment]
I am still confused about the details of solution

**Comment by matt-bernhardt** [comment]
This sounds like it would solve the problem I've had when starting to work with Jupyter, but I'm not sure how to check out this branch (via pip) to confirm this.

I'm trying to use Jupyter with Windows 10 using any of Chrome, Firefox, or Edge. All three browsers exhibit the same behavior - a blank browser window, no apparent errors in the terminal console, but warnings and errors in the browser console relating to MIME type problems. I'm including screenshots here for reference.

image
image
image

**Comment by minrk** [comment]
Excellent, thank you!

**Comment by minrk** [comment]
@meeseeksdev backport to 5.7.x

**Comment by monocongo** [comment]
I have tried moving my version of notebook back to 5.7.4 but no luck so far. Can someone comment as to how I can build from source into my conda environment, in order to leverage the fix described in the comments above? Or will this fix be included in an upcoming release that I can utilize via `conda update notebook`?

BTW I have tried the following command, but it failed with a compilation error regarding a missing "bower" (which I was not able to find/install, so I gave up):

`$ pip install git+git://github.com/jupyter/notebook@5.7.x`

Thanks in advance for any assistance with this!

**Comment by minrk** [comment]
Working on publishing 5.7.7 now.

nodejs and npm are needed to build notebook from source.

**Comment by jamesmyatt** [comment]
Is there a way of fixing the root cause, i.e. that the registry has the wrong mime type?

**Comment by minrk** [comment]
I'm not a Windows expert, but from [this](https://stackoverflow.com/questions/2549015/finding-a-mime-type-for-a-file-on-windows), it appears to be in `HKEY_CLASSES_ROOT\MIME\Database\Content Type`. I *think* the root cause is installation of certain software may modify this database, perhaps as a way of associating itself as an opener for file extensions.

**Comment by minrk** [comment]
5.7.7 is [on pypi](https://pypi.org/project/notebook/#files)

**Comment by jamesmyatt** [comment]
Thanks, @minrk . I found it in `HKCR\.js\Content Type` and changing that also fixed this problem.

**Comment by EAly** [comment]
Can anyone help how to apply this solution, i.e how to "add in a mimetypes override for .js files"?!
