### ISSUE TITLE
type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by jiapei100** [jupyter/notebook#3595]
OS: Ubuntu 18.04
Python: default python 3.6.5 grabbed from repository
pip3: 

> $ pip3 --version
> pip 10.0.1 from /home/jiapei/.local/lib/python3.6/site-packages/pip (python 3.6)

> $ jupyter-notebook
> Traceback (most recent call last):
>   File "/usr/bin/jupyter-notebook", line 11, in <module>
>     load_entry_point('notebook==5.2.2', 'console_scripts', 'jupyter-notebook')()
>   File "/home/jiapei/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/home/jiapei/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
>     return ep.load()
>   File "/home/jiapei/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
>     return self.resolve()
>   File "/home/jiapei/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3/dist-packages/notebook/notebookapp.py", line 43, in <module>
>     ioloop.install()
>   File "/usr/lib/python3/dist-packages/zmq/eventloop/ioloop.py", line 210, in install
>     assert (not ioloop.IOLoop.initialized()) or \
> AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by vkryukov** [comment]
I have the same problem on on Mac OS X 10.13.4:

```
Victors-MacBook-Pro:coursera-ml-ang victor$ jupyter --version
4.4.0
Victors-MacBook-Pro:coursera-ml-ang victor$ python3 --version
Python 3.6.5
Victors-MacBook-Pro:coursera-ml-ang victor$ jupyter-notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
Victors-MacBook-Pro:coursera-ml-ang victor$ 
```

**Comment by takluyver** [comment]
If you've got tornado v5 then you need to upgrade pyzmq to v17.

**Comment by shashank42** [comment]
If you're using anaconda installation of python this works
conda install -c anaconda pyzmq

**Comment by ptocca** [comment]
For me `conda install -c anaconda pyzmq` did not solve the issue.
I had to get pyzmq v17 from conda-forge with:
conda install -c conda-forge pyzmq

**Comment by luis-pereira-data** [comment]
Seeing the same issue when launching Jupyter notebook from the anaconda launcher:
![image](https://user-images.githubusercontent.com/566802/44018624-48e380fa-9ed4-11e8-9912-87a4ae0ce9a4.png)

**Comment by luis-pereira-data** [comment]
conda install -c anaconda pyzmq has solved my issue.

**Comment by iuryt** [comment]
`conda install -c anaconda pyzmq` has solved my issue   [2]

**Comment by kwijik** [comment]
`conda install -c anaconda pyzmq ` does NOT solved my problem. It still crashes.

**Comment by rohitpattnaik** [comment]
conda install -c conda-forge pyzmq solved my issue ... Thanks :)

**Comment by TianyiQiu** [comment]
conda install -c anaconda pyzmq solved my problem
Thank you a lot.

**Comment by xiapengchng** [comment]
conda install -c anaconda pyzmq solved my problem
Thank you a lot.

**Comment by liudongqing** [comment]
after installed pyzmq, it reported:
>ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

**Comment by Geekhamza** [comment]
conda install -c anaconda pyzmq solved my problem
Thank you a lot.

**Comment by sumantk** [comment]
I am not working on Conda. How can I achieve the same using pip? I am working on Mac OS.

**Comment by priya-gitTest** [comment]
Doing this [conda install -c anaconda pyzmq] solved the issue for me too when i got the error below. Wondering why it happened all of a sudden that half an hour ago i was able to run my notebooks and then i got the error Kernel is dead and then even after restarting, I was not able to run the Jupyter Notebooks until i did the conda install as mentioned above.

Traceback (most recent call last):
File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\notebook\notebookapp.py", line 45, in 
ioloop.install()
File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\zmq\eventloop\ioloop.py", line 210, in install
assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by dandanxu** [comment]
thanks, `conda install -c anaconda pyzmq` fixed this issue for me!

**Comment by minrk** [comment]
@sumantk updating pyzmq and notebook with pip should work, too: `pip install --upgrade pyzmq notebook`. In all cases, the issue here is that the `tornado` package is new and `pyzmq` and/or `notebook` are out-of-date. The current versions of all these packages work well together, so if you see this issue, make sure pyzmq and notebook are up to date via whichever mechanism you have chosen to install these packages.

**Comment by jabalazs** [comment]
Thank you @minrk, 
`pip install --upgrade pyzmq notebook` did the trick.

**Comment by Chryzanthemum** [comment]
Just another voice in the wilderness but pip install --upgrade pyzmq notebook did it for me after trying everything else.

**Comment by sarunasb** [comment]
`pip install --upgrade pyzmq notebook` 
didn't help, had to do 
`python3 -m pip install --upgrade pyzmq notebook`

System: Ubuntu 18.04, Python 3.6.7 from standard Ubuntu repositories, followed [JupyterHub Quick Start](https://jupyterhub.readthedocs.io/en/latest/quickstart.html).

**Comment by Mira-Qiu** [comment]
conda install -c anaconda pyzmq has solved my issue.

**Comment by dianags** [comment]
Had the same problem when updating python to 3.6. 

`conda install -c anaconda pyzmq` solved my issue too.

**Comment by munick** [comment]
`conda install pyzmq==17.1` did it for me. Upgrading to 17.0 gave me the importerror with `libsodium.so.23` that others have mentioned.

**Comment by BoKyeong-Kim** [comment]
`conda install -c anaconda pyzmq` has solved my issue. thank you!!! :)

**Comment by rebeen** [comment]
conda install tornado=4.5.3 solved my problem :100:

**Comment by pallasathena92** [comment]
> conda install -c anaconda pyzmq 
have solved my issue

this is the lines in my cmd. 
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: \
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::astropy==1.3.2=np112py36_0
  - defaults/win-64::blaze==0.10.1=py36_0
  - defaults/win-64::bottleneck==1.2.1=np112py36_0
  - defaults/win-64::ipykernel==4.6.1=py36_0
  - defaults/win-64::ipython==5.3.0=py36_0
  - defaults/win-64::ipywidgets==6.0.0=py36_0
  - defaults/win-64::jupyter==1.0.0=py36_3
  - defaults/win-64::jupyter_client==5.0.1=py36_0
  - defaults/win-64::jupyter_console==5.1.0=py36_0
  - defaults/win-64::jupyter_core==4.3.0=py36_0
  - defaults/win-64::line_profiler==2.1.2=py36hfa6e2cd_0
  - defaults/win-64::nbconvert==5.1.1=py36_0
  - defaults/win-64::nbformat==4.3.0=py36_0
  - conda-forge/label/gcc7/noarch::node2vec==0.1.1=py_1
  - defaults/win-64::notebook==5.0.0=py36_0
  - defaults/win-64::numba==0.33.0=np112py36_0
  - defaults/win-64::odo==0.5.0=py36_1
  - defaults/win-64::plotly==3.4.2=py36h28b3542_0
  - defaults/win-64::pytables==3.2.2=np112py36_4
  - defaults/win-64::pywavelets==0.5.2=np112py36_0
  - defaults/win-64::qtconsole==4.3.0=py36_0
  - defaults/win-64::scikit-image==0.13.0=np112py36_0
  - defaults/win-64::seaborn==0.8.1=py36h9b69545_0
  - defaults/win-64::spyder==3.1.4=py36_0
  - defaults/win-64::statsmodels==0.8.0=np112py36_0
  - defaults/win-64::traitlets==4.3.2=py36_0
  - defaults/win-64::widgetsnbextension==2.0.0=py36_0
done

**Comment by scruffy403** [comment]
> If you're using anaconda installation of python this works
> conda install -c anaconda pyzmq

I'm not using anaconda but was still able to use this info to resolve my issue. Thanks!!

`pip3 install pyzmq`

worked in my case.

**Comment by r1n53-4nd-r3p347** [comment]
conda install -c anaconda pyzmq solved my issue too.

**Comment by gauravkoradiya** [comment]
> Thank you @minrk,
> `pip install --upgrade pyzmq notebook` did the trick.
WOW...Isuue resolves

**Comment by shencebebetterme** [comment]
On my Ubuntu 18.04 laptop, the same problem is solved by `pip3 uninstall tornado` which uninstalls the tornado-6.0.2. However there's still a tornado-4.x.x installed on my machine as can be seen from the synaptic package manager. So the problem is either caused by a conflict of different versions of tornado, or by a default newer tornado.

**Comment by NateZimmer** [comment]
I installed anaconda fresh from the recommended W10 binary and got this error.
"Solutions" like `conda install -c anacond` are not legit fixes for a fresh install. Why is this issue closed?

**Comment by waealobidallah** [comment]
`pip install --upgrade pyzmq` solved the problem for me

**Comment by Proletariat99** [comment]
`conda install -c anaconda pyzmq ` failed to resolve the problem, but `conda install -c conda-forge pyzmq`.  It installed v18.1.0 of pyzmq.

**Comment by yhuag** [comment]
> @sumantk updating pyzmq and notebook with pip should work, too: `pip install --upgrade pyzmq notebook`. In all cases, the issue here is that the `tornado` package is new and `pyzmq` and/or `notebook` are out-of-date. The current versions of all these packages work well together, so if you see this issue, make sure pyzmq and notebook are up to date via whichever mechanism you have chosen to install these packages.

This is awesome.

**Comment by kkairu** [comment]
> If you've got tornado v5 then you need to upgrade pyzmq to v17.

pyzmq upgrade to v18 works OK.

**Comment by SaraTohidi** [comment]
`conda install -c anaconda pyzmq`  has solved my issue, too! Thanks!

**Comment by yunchenran** [comment]
conda install tornado=4.5.3 solved my issue, thx~

**Comment by ChengHsiuChi** [comment]
conda install tornado=4.5.3 solved my problem!

**Comment by wlongxiang** [comment]
> conda install -c anaconda pyzmq

This solves my issue too

**Comment by alfo1995** [comment]
conda install -c anaconda pyzmq solved my problem, thanks!

**Comment by GopaluniRohit** [comment]
conda install -c anaconda pyzmq has solved my issue

**Comment by cgironda** [comment]
Hi guys,

The command below also solved my problem for the base environment.
`conda install -c anaconda pyzmq`
However, I was wondering if it must be done for every virtual environemnt every time Jupyther crashes for some reason.

Any ideas?

**Comment by kevin-bates** [comment]
I believe pyzmq has a fairly involved/complicated installation due to its low-level nature and, yes, it could apply to your different virtual environments.  So, should the traceback tend to reflect things related to pyzmq, yes, it should be considered one of the tools in your toolbox for troubleshooting issues.  That said, this kind of thing only tends to occur when spanning versions and cross-dependencies are in play, so it shouldn't be your "go to" _every time Jupyther crashes for some reason_.

**Comment by pravin126** [comment]
conda install -c anaconda pyzmq Soled my problem Thanks.

**Comment by ace-racer** [comment]
I tried the above commands, but it still did not work. I was finally able to run jupyter notebook in a custom conda environment after running `conda install -c anaconda ipykernel`

**Comment by drekisen** [comment]
Tengo una Raspberry Pi 3B y estaba instalando Jupyter con el mismo error, que no abría el notebook pero con:      
pip3 install --ignore-installed pyzmq

Ya abrió el notebook

**Comment by axc888** [comment]
Thank you for the command. Really solved the issue.
conda install -c anaconda pyzmq

**Comment by yusufadell** [comment]
this also worked for me 
`pip install --upgrade pyzmq`
