### ISSUE TITLE
from notebook import notebookapp  not working in version 7.0.2

### ISSUE THREAD

**Issue by anuragdogra2192** [jupyter/notebook#7010]
## Description
from notebook import notebookapp, this module is not available on 7.0.2 

## Reproduce
from notebook import notebookapp as _notebookapp

Output:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[10], line 1
----> 1 from notebook import notebookapp as _notebookapp

ImportError: cannot import name 'notebookapp' from 'notebook'

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior
from notebook import notebookapp - Should be loaded
_notebookapp.list_running_servers()  and provide the running servers

## Context

- Operating System and version:  Windows 10
- Browser and version: 

- Jupyter Notebook version:  notebook         : 7.0.2
Selected Jupyter core packages...

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>
